<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-25 at 23:34:38.
 */
require 'bootstrap.php';
require 'class_intervat.php';

class IntervatTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Intervat
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Intervat;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Intervat::append_root
     * @todo   Implement testAppend_root().
     */
    public function testAppend_root()
    {
               $this->object->append_root();
        $result = $this->object->domdoc->saveXML();
        $must_march = '<?xml version="1.0" encoding="ISO-8859-1"?>     
	<ns2:ClientListingConsignment xmlns="http://www.minfin.fgov.be/InputCommon" xmlns:ns2="http://www.minfin.fgov.be/ClientListingConsignment" ClientListingsNbr="1">';
        $this->assertContains('<?xml version="1.0" encoding="ISO-8859-1"?>', $result);
        $this->assertContains('<ns2:ClientListingConsignment', $result);
        $this->assertContains('xmlns="http://www.minfin.fgov.be/InputCommon"', $result);
        $this->assertContains('xmlns:ns2="http://www.minfin.fgov.be/ClientListingConsignment"', $result);
        $this->assertContains('ClientListingsNbr="1"', $result);
    }

    /**
     * @covers Intervat::append_representative
     * @todo   Implement testAppend_representative().
     */
    public function testAppend_representative()
    {
        $this->object->append_root();
        $this->object->append_representative();
        $result = $this->object->domdoc->saveXML();
        $this->assertContains('ns2:Representative',$result);
        var_dump($result);
    }

    /**
     * @covers Intervat::append_client_listing
     * @todo   Implement testAppend_client_listing().
     */
    public function testAppend_client_listing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Intervat::append_declarant
     * @todo   Implement testAppend_declarant().
     */
    public function testAppend_declarant()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Intervat::append_listing
     * @todo   Implement testAppend_listing().
     */
    public function testAppend_listing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
