<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-07 at 22:27:24.
 */
class Transform_ClientTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Transform_Client
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Transform_Client;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Transform_Client::compute_value
     * @todo   Implement testCompute_value().
     */
    public function testCompute_value()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transform_Client::set_comment
     * @todo   Implement testSet_comment().
     */
    public function testSet_comment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
