<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-25 at 23:34:38.
 */
class IntervatTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Intervat
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Intervat;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Intervat::append_root
     * @todo   Implement testAppend_root().
     */
    public function testAppend_root()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Intervat::append_representative
     * @todo   Implement testAppend_representative().
     */
    public function testAppend_representative()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Intervat::append_client_listing
     * @todo   Implement testAppend_client_listing().
     */
    public function testAppend_client_listing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Intervat::append_declarant
     * @todo   Implement testAppend_declarant().
     */
    public function testAppend_declarant()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Intervat::append_listing
     * @todo   Implement testAppend_listing().
     */
    public function testAppend_listing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
